modLoader="javafml"
loaderVersion="[31,)"
license="LGPL"
issueTrackerURL="https://github.com/MKuckert/eye-of-dragons/issues"
[[mods]]
modId="eyeofdragons"
version="${file.jarVersion}"
displayName="Eye of Dragons"
logoFile="assets/eyeofdragons/logo.png"
credits=""
authors="Martin Kuckert"
description='''
Adds Eye of Dragons to find Ice, Fire and Lightning dragons
'''

[[dependencies.eyeofdragons]]
    modId="iceandfire"
    mandatory=true
    versionRange="[2.0.3,)"
    ordering="AFTER"
    side="BOTH"

# citadel is required by iceandfire
[[dependencies.eyeofdragons]]
    modId="citadel"
    mandatory=true
    versionRange="[1.1.11,)"
    ordering="AFTER"
    side="BOTH"
